name: scrape

on:
  schedule:
    # 8 a.m. every day
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  scrape-latest:
    name: scrape-latest
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install selenium requests pandas beautifulsoup4 webdriver-manager
          
      - id: install-chromedriver
        name: Install chromedriver
        uses: nanasess/setup-chromedriver@master

      - name: Scrape and log
        shell: bash
        run: |
          python git_scraping.py
      - name: Add and commit and push
        run: |
          git fetch
          git pull
          git add --all
          git config user.name "Automated"
          git commit -m "Latest data" 
          git push